config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: { registrations: "customers/registrations" }

  resources :logins, only: :index do
    get "/", to: "logins#show"
  end

  get "/accounts/:account_id", to: "accounts#show", as: "account"

  post   "create_connection",  to: "logins#create",    as: "create_connection"
  delete "destroy_connection", to: "logins#destroy",   as: "destroy_connection"
  put    "reconnect",          to: "logins#reconnect", as: "reconnect"
  put    "refresh",            to: "logins#refresh",   as: "refresh"
  get    "success",            to: "logins#success",   as: "success"

  root "logins#index"
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :login
  has_many :transactions, primary_key: "account_id", dependent: :destroy

  validates :account_id, uniqueness: true, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :logins, primary_key: "customer_id"

  validates :email, presence: true
end

app/models/login.rb
class Login < ApplicationRecord
  belongs_to :customer
  has_many :accounts, primary_key: "login_id", dependent: :destroy

  validates :login_id, uniqueness: true, presence: true

  def fetch
    fetch_accounts
    fetch_transactions
  end

  private

  def fetch_accounts
    self.accounts.destroy_all if self.accounts.any?

    response = SaltedgeClient.fetch_accounts(self)
    response.fetch("data").each do |account_data|
      posted_count  = account_data.dig("extra", "transactions_count", "posted").to_i
      pending_count = account_data.dig("extra", "transactions_count", "pending").to_i

      account = Account.new(
        account_id:         account_data.fetch("id"),
        login_id:           account_data.fetch("connection_id"),
        name:               account_data.fetch("name"),
        balance:            account_data.fetch("balance"),
        currency:           account_data.fetch("currency_code"),
        nature:             account_data.fetch("nature"),
        transactions_count: posted_count + pending_count
      )

      account.save!
    end
  end

  def fetch_transactions
    self.accounts.each do |account|
      response     = SaltedgeClient.fetch_transactions(account)
      response.fetch("data").each do |transaction_data|
        transaction = Transaction.new(
          transaction_id: transaction_data.fetch("id"),
          account_id:     transaction_data.fetch("account_id"),
          status:         transaction_data.fetch("status"),
          currency:       transaction_data.fetch("currency_code"),
          amount:         transaction_data.fetch("amount"),
          description:    transaction_data.fetch("description"),
          made_on:        transaction_data.fetch("made_on"),
          category:       transaction_data.fetch("category")
        )

        transaction.save!
      end
    end
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account

  validates :transaction_id, uniqueness: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  add_breadcrumb "Connections", :logins_path

  def show
    @account      = Account.find(params[:account_id])
    @transactions = @account.transactions
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_customer!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(user)
    session[:requested_url] || root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/customers/registrations_controller.rb
class Customers::RegistrationsController < Devise::RegistrationsController
  def create
    super
    email    = params[:customer]["email"]
    customer = Customer.find_by(email: email)

    response = SaltedgeClient.create_customer(email)

    customer.customer_id = response.dig("data", "id")
    customer.save
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  add_breadcrumb "Connections", :logins_path

  def index
    @logins = current_customer.logins
  end

  def show
    @login    = Login.find(params[:login_id])
    @accounts = @login.accounts
  end

  def create
    response    = SaltedgeClient.create_connection(current_customer.customer_id)
    connect_url = response.dig("data","connect_url")

    redirect_to connect_url
  rescue => error
    handle_error(error)
  end

  def reconnect
    response    = SaltedgeClient.reconnect(params[:login_id])
    connect_url = response.dig("data", "connect_url")

    redirect_to connect_url
  rescue => error
    handle_error(error)
  end

  def refresh
    login = Login.find(params[:login_id])

    if login.next_refresh_possible_at < Time.current.to_datetime
      response    = SaltedgeClient.refresh(login.login_id)
      connect_url = response.dig("data", "connect_url")

      redirect_to connect_url
    else
      flash.notice = "Next refresh will be possible at #{login.next_refresh_possible_at.strftime("%Y/%m/%d %H:%M:%S")}"
      redirect_to logins_path
    end
  rescue => error
    handle_error(error)
  end

  def destroy
    SaltedgeClient.destroy(params[:login_id])
    Login.find(params[:login_id]).destroy

    redirect_to logins_path
  end

  def success
    handle_callback
    redirect_to logins_path
  end

  private

  def handle_callback
    response = SaltedgeClient.fetch_connections(current_customer.customer_id)

    login = create_or_update_login(response)
    login.fetch
  end

  def create_or_update_login(response)
    updated_login  = response.fetch("data").max_by { |connection| connection["updated_at"].to_datetime }
    existing_login = Login.find_by(login_id: updated_login.fetch("id"))

    if existing_login
      login = existing_login
      login.update!(
        status:                   updated_login.fetch("status"),
        last_success_at:          updated_login.fetch("last_success_at"),
        next_refresh_possible_at: updated_login.fetch("next_refresh_possible_at")
      )
    else
      login = Login.create(
        login_id:                 updated_login.fetch("id"),
        customer_id:              updated_login.fetch("customer_id"),
        provider_name:            updated_login.fetch("provider_name"),
        country_code:             updated_login.fetch("country_code"),
        status:                   updated_login.fetch("status"),
        last_success_at:          updated_login.fetch("last_success_at"),
        next_refresh_possible_at: updated_login.fetch("next_refresh_possible_at")
      )
      login.save!
    end

    login
  end

  def handle_error(error)
    if error.try(:response).try(:body)
      response = JSON.parse(error.response.body)
      flash.alert = response["error"]["message"]
    else
      flash.alert = "Something went wrong"
    end

    redirect_to logins_path
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/accounts/_account.html.erb
<tr>
    <th>
        <%= account.account_id %>
    </th>
    <td>
        <%= account.name %>
    </td>
    <td>
        <%= account.balance %>
    </td>
    <td>
        <%= account.currency %>
    </td>
    <td>
        <%= account.nature %>
    </td>
    <td>
        <%= link_to account.transactions_count, account %>
    </td>
</tr>

app/views/accounts/show.html.erb
<div class="container">
    <table class="table table-responsive">
        <thead class="thead-light">
            <tr>
                <th>ID</th>
                <th>Made On</th>
                <th>Description</th>
                <th>Category</th>
                <th>Amount</th>
                <th>Currency</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            <%= render @transactions %>
        </tbody>
    </table>
</div>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-sm bg-light navbar-light">
    <% if customer_signed_in? %>
    <ul class="navbar-nav">
        <li class="nav-item active nav-link">
            Greetings,
            <%= current_customer.username %>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
            <%= button_to "Logout", destroy_customer_session_path, method: :delete, class: "btn btn-link" %>
        </li>
        <li class="nav-item active">
            <%= button_to "Create connection", create_connection_path(current_customer), method: :post, class: "btn btn-link" %>
        </li>
    </ul>
    <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>SaltyJenea</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
</head>

<body>
    <%= render "navbar" %>
    <ol class="breadcrumb">
        <%= render_breadcrumbs :tag => :li, :separator => " / " %>
    </ol>
    <%= yield %>
    <% if notice %>
    <p class="alert alert-success">
        <%= notice %>
    </p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger">
        <%= alert %>
    </p>
    <% end %>
</body>

</html>

app/views/logins/_login.html.erb
<tr>
    <th>
        <%= login.login_id %>
    </th>
    <td>
        <%= login.customer_id %>
    </td>
    <td>
        <%= login.country_code %>
    </td>
    <td>
        <%= login.provider_name %>
    </td>
    <td>
        <%= login.status %>
    </td>
    <td>
        <%= link_to login.accounts.size, login %>
    </td>
    <td>
        <%= link_to "Reconnect", reconnect_path(login_id: login.login_id), method: :put, class: "btn btn-outline-success btn-sm"%>
    </td>
    <td>
        <%= link_to "Refresh", refresh_path(login_id: login.login_id), method: :put, class: "btn btn-outline-primary btn-sm" %>
    </td>
    <td>
        <%= link_to "Destroy", destroy_connection_path(login_id: login.login_id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger btn-sm" %>
    </td>
</tr>

app/views/logins/index.html.erb
<div class="container">
    <table class="table table-responsive">
        <thead class="thead-light">
            <th>ID</th>
            <th>Customer ID</th>
            <th>Country Code</th>
            <th>Provider Name</th>
            <th>Status</th>
            <th>Accounts</th>
            <th></th>
            <th></th>
            <th></th>
        </thead>
        <tbody>
            <%= render @logins %>
        </tbody>
    </table>
</div>

app/views/logins/show.html.erb
<div class="container">
    <table class="table table-responsive">
        <thead class="thead-light">
            <th>ID</th>
            <th>Name</th>
            <th>Balance</th>
            <th>Currency</th>
            <th>Nature</th>
            <th>Transactions</th>
        </thead>
        <tbody>
            <%= render @accounts %>
        </tbody>
    </table>
</div>

app/views/transactions/_transaction.html.erb
<tr>
    <td>
        <%= transaction.transaction_id %>
    </td>
    <td>
        <%= transaction.made_on %>
    </td>
    <td>
        <%= transaction.description %>
    </td>
    <td>
        <%= transaction.category %>
    </td>
    <td>
        <%= transaction.amount %>
    </td>
    <td>
        <%= transaction.currency %>
    </td>
    <td>
        <%= transaction.status %>
    </td>
</tr>

app/views/transactions/_transactions.html.erb
<tr>
    <td>
        <%= transaction.transaction_id %>
    </td>
    <td>
        <%= transaction.made_on %>
    </td>
    <td>
        <%= transaction.status %>
    </td>
    <td>
        <%= transaction.category %>
    </td>
    <td>
        <%= transaction.description %>
    </td>
    <td>
        <%= transaction.amount %>
    </td>
    <td>
        <%= transaction.currency %>
    </td>
</tr>